version: 2
updates:
    - package-ecosystem: github-actions
      directory: "/"
      schedule:
          interval: daily
          time: "03:00"
          timezone: Europe/Paris
      open-pull-requests-limit: 10
    - package-ecosystem: composer
      directory: "/"
      schedule:
          interval: weekly
          day: saturday
          time: "03:00"
          timezone: Europe/Paris
      open-pull-requests-limit: 10
      labels:
          - dependencies
          - php
      allow:
          - dependency-type: direct
          - dependency-type: indirect
